import type { Project } from "@/lib/types"

export const mockProjectDetails: Project[] = [
  {
    id: "PRJ-001",
    name: "Westside Fiber Deployment",
    projectManager: "John Doe",
    location: "Westside District",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    status: "In Progress",
    budget: 1500000,
    customer: "City of Westside",
    customerContact: "Jane Smith",
    customerEmail: "jane.smith@westside.gov",
    customerPhone: "+1 (555) 123-4567",
    description:
      "Comprehensive fiber optic network deployment across the Westside District to provide high-speed internet access to residential and commercial areas.",
    overallProgress: 65,
    budgetUsed: 975000,
    activeTasksCount: 12,
    completedTasksCount: 8,
    currentPhaseName: "Network Installation",
    currentPhaseProgress: 75,
    phase: "WIP - Civils Work",
    progress: 65,
    projectPhases: [
      {
        name: "Site Survey and Planning",
        duration: "2 weeks",
        description: "Conduct comprehensive site surveys and create detailed deployment plans",
        deliverables: "Site survey reports, network topology maps, equipment placement plans",
        status: "Completed",
        isFlagged: false,
        progress: 100,
      },
      {
        name: "Permits and Approvals",
        duration: "3 weeks",
        description: "Obtain all necessary permits and regulatory approvals",
        deliverables: "Building permits, utility crossing agreements, environmental clearances",
        status: "Completed",
        isFlagged: false,
        progress: 100,
      },
      {
        name: "Network Installation",
        duration: "8 weeks",
        description: "Install fiber optic cables, equipment, and infrastructure",
        deliverables: "Installed fiber network, equipment racks, power systems",
        status: "Started",
        isFlagged: true,
        flagReason: "Weather delays causing installation slowdowns",
        progress: 75,
      },
      {
        name: "Testing and Commissioning",
        duration: "2 weeks",
        description: "Test all network components and commission the system",
        deliverables: "Test reports, system documentation, go-live approval",
        status: "Pending",
        isFlagged: false,
        progress: 0,
      },
      {
        name: "Customer Activation",
        duration: "1 week",
        description: "Activate customer connections and provide service",
        deliverables: "Active customer connections, service documentation",
        status: "Pending",
        isFlagged: false,
        progress: 0,
      },
    ],
  },
  {
    id: "PRJ-002",
    name: "Downtown Network Expansion",
    projectManager: "Sarah Johnson",
    location: "Downtown Core",
    startDate: "2024-02-01",
    endDate: "2024-05-15",
    status: "Completed",
    budget: 2000000,
    customer: "Downtown Business Association",
    customerContact: "Mike Rodriguez",
    customerEmail: "mike.rodriguez@downtown.org",
    customerPhone: "+1 (555) 987-6543",
    description:
      "Expansion of existing fiber network to support increased bandwidth demands in the downtown business district.",
    overallProgress: 100,
    budgetUsed: 1950000,
    activeTasksCount: 0,
    completedTasksCount: 15,
    currentPhaseName: "Project Complete",
    currentPhaseProgress: 100,
    phase: "Handover",
    progress: 100,
    projectPhases: [
      {
        name: "Network Assessment",
        duration: "1 week",
        description: "Assess current network capacity and expansion requirements",
        deliverables: "Capacity analysis, expansion recommendations",
        status: "Completed",
        isFlagged: false,
        progress: 100,
      },
      {
        name: "Infrastructure Upgrade",
        duration: "6 weeks",
        description: "Upgrade existing infrastructure and add new capacity",
        deliverables: "Upgraded network equipment, increased fiber capacity",
        status: "Completed",
        isFlagged: false,
        progress: 100,
      },
      {
        name: "Service Migration",
        duration: "2 weeks",
        description: "Migrate existing services to upgraded infrastructure",
        deliverables: "Migrated services, updated documentation",
        status: "Completed",
        isFlagged: false,
        progress: 100,
      },
    ],
  },
  {
    id: "PRJ-003",
    name: "Rural Connectivity Phase 2",
    projectManager: "Mike Wilson",
    location: "Rural Areas",
    startDate: "2024-01-10",
    endDate: "2024-04-30",
    status: "In Progress",
    budget: 1200000,
    customer: "Rural Development Authority",
    customerContact: "Lisa Chen",
    customerEmail: "lisa.chen@rural.gov",
    customerPhone: "+1 (555) 456-7890",
    description: "Second phase of rural fiber deployment to connect underserved communities.",
    overallProgress: 30,
    budgetUsed: 360000,
    activeTasksCount: 8,
    completedTasksCount: 3,
    currentPhaseName: "Pole Installation",
    currentPhaseProgress: 45,
    phase: "IP - Planning",
    progress: 35,
    projectPhases: [
      {
        name: "Route Planning",
        duration: "3 weeks",
        description: "Plan optimal routes for rural fiber deployment",
        deliverables: "Route maps, cost estimates, timeline",
        status: "Completed",
        isFlagged: false,
        progress: 100,
      },
      {
        name: "Pole Installation",
        duration: "10 weeks",
        description: "Install utility poles for fiber optic cables",
        deliverables: "Installed utility poles, foundation work",
        status: "Started",
        isFlagged: true,
        flagReason: "Land access issues with some property owners",
        progress: 45,
      },
      {
        name: "Cable Installation",
        duration: "8 weeks",
        description: "Install fiber optic cables on poles",
        deliverables: "Installed fiber cables, splice enclosures",
        status: "Pending",
        isFlagged: false,
        progress: 0,
      },
      {
        name: "Equipment Installation",
        duration: "4 weeks",
        description: "Install network equipment and customer premises equipment",
        deliverables: "Network equipment, customer installations",
        status: "Pending",
        isFlagged: false,
        progress: 0,
      },
    ],
  },
  {
    id: "PRJ-004",
    name: "Industrial Park Installation",
    projectManager: "Emily Chen",
    location: "Industrial Park",
    startDate: "2024-03-01",
    endDate: "2024-09-30",
    status: "Planned",
    budget: 800000,
    customer: "Industrial Park Authority",
    customerContact: "David Wong",
    customerEmail: "david.wong@industrialpark.org",
    customerPhone: "+1 (555) 234-5678",
    description:
      "New fiber installation throughout the industrial park to support manufacturing and logistics operations.",
    overallProgress: 10,
    budgetUsed: 80000,
    activeTasksCount: 2,
    completedTasksCount: 1,
    currentPhaseName: "Site Survey",
    currentPhaseProgress: 60,
    phase: "IP - Initiation",
    progress: 10,
    projectPhases: [
      {
        name: "Site Survey",
        duration: "2 weeks",
        description: "Comprehensive site survey of industrial park",
        deliverables: "Survey reports, site maps, infrastructure assessment",
        status: "Started",
        isFlagged: false,
        progress: 60,
      },
      {
        name: "Design and Planning",
        duration: "3 weeks",
        description: "Network design and implementation planning",
        deliverables: "Network design documents, implementation plan, timeline",
        status: "Pending",
        isFlagged: false,
        progress: 0,
      },
      {
        name: "Permits and Approvals",
        duration: "4 weeks",
        description: "Obtain necessary permits and regulatory approvals",
        deliverables: "Approved permits, regulatory clearances",
        status: "Pending",
        isFlagged: false,
        progress: 0,
      },
      {
        name: "Implementation",
        duration: "12 weeks",
        description: "Full implementation of fiber network",
        deliverables: "Installed network, testing reports",
        status: "Pending",
        isFlagged: false,
        progress: 0,
      },
    ],
  },
]
